version: '3.9'

services:
  payments-microservice:
    image: payment_microservice_image
    ports:
      - "8072:8080"

    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  ordering-microservice:
    image: ordering_microservice_image
    ports:
      - "8073:8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  customer-micrroservice:
    image: customer_microservice_image
    ports:
      - "8071:8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  overlay-network-eureka:
    external: true

